apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: java-cicd-demo
  name: java-cicd-demo
  namespace: cicd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-cicd-demo
  template:
    metadata:
      labels:
        app: java-cicd-demo
    spec:
      containers:
        - image: registry.cn-beijing.aliyuncs.com/pzyhub/java-cicd-demo:v8
          imagePullPolicy: IfNotPresent
          name: java-cicd-demo
          resources:
            limits:
              cpu: 100m
              memory: 250Mi
            requests:
              cpu: 10m
              memory: 200Mi
          volumeMounts:
            - mountPath: /etc/localtime
              name: volume-localtime
      volumes:
        - hostPath:
            path: /etc/localtime
          name: volume-localtime
